name: fe-qa-automation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options: [dev, qa]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      ENV: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout QA Automation Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chromium --with-deps

      # -------------------------------------------------------
      # RUN TESTS (Reports only)
      # -------------------------------------------------------
      # - name: Run Regression Tests
      #   run: npx playwright test tests/Regression_TestCases_Sprint1_2.spec.js --reporter=html
      #   env:
      #     PLAYWRIGHT_HTML_REPORT: regression-report-folder

      - name: Run Smoke Tests
        run: npx playwright test tests/Smoke_TestCase_Sprint3.spec.js --reporter=html
        env:
          PLAYWRIGHT_HTML_REPORT: smoke-report-folder
          YOPMAIL_USER: patricia

      - name: Run Functional Tests
        run: npx playwright test tests/Functional_TestCase_Sprint3.spec.js --reporter=html
        env:
          PLAYWRIGHT_HTML_REPORT: functional-report-folder

      # -------------------------------------------------------
      # UPLOAD REPORTS AS ARTIFACTS
      # -------------------------------------------------------
      # - name: Upload Regression Report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Regression-Report
      #     path: regression-report-folder/
      #     retention-days: 14

      - name: Upload Smoke Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Smoke-Report
          path: smoke-report-folder/
          retention-days: 14

      - name: Upload Functional Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Functional-Report
          path: functional-report-folder/
          retention-days: 14